[package]
name = "call_scribe"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.14.1", features = ["backend-winit", "renderer-skia-opengl"] }

[build-dependencies]
slint-build = "1.14.1"
